server:
  port: ${sba.server.port}

sbapsd:
  providers:
    s1:
      type: registry
      labels:
        __test: no-filters
    s2:
      type: registry
      labels:
        __test: filter-status
      filters:
        - type: status
          params:
            value: UP
    s3:
      type: registry
      labels:
        __test: filter-app-name
      filters:
        - type: app-name
          params:
            value: app-1
    s4:
      type: registry
      labels:
        __test: filter-app-name-status
      filters:
        - type: app-name
          params:
            value: app-1
        - type: status
          params:
            value: UP
