name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:
  test-v1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sba-version: [ '1.4.6', '1.5.7' ]
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle run server
        run: nohup ./gradlew runV1SBAServer -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8081 &

      - name: Await server up
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: http://localhost:8081/health
          responseCode: 200,500
          timeout: 300000
          interval: 1000

      - name: Gradle test
        run: ./gradlew :sbapsd-testing:test -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8081

  test-v2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sba-version: [ '2.4.4', '2.5.6', '2.6.11', '2.7.10' ]
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle run server
        run: nohup ./gradlew runV2SBAServer -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8082 &

      - name: Await server up
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: http://localhost:8082/actuator/health
          responseCode: 200,500
          timeout: 300000
          interval: 1000

      - name: Gradle test
        run: ./gradlew :sbapsd-testing:test -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8082

  test-v3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sba-version: [ '3.0.0' ]
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle run server
        run: nohup ./gradlew runV3SBAServer -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8083 &

      - name: Await server up
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: http://localhost:8083/actuator/health
          responseCode: 200,500
          timeout: 300000
          interval: 1000

      - name: Gradle test
        run: ./gradlew :sbapsd-testing:test -Psba.version=${{ matrix.sba-version }} -Psba.server.port=8083

  build-jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: |
            sbapsd-standalone-v2/build/libs/*.jar
            sbapsd-standalone-v3/build/libs/*.jar
          retention-days: 5

  build-native-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: "22.3.1"
          java-version: "19"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: "true"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle nativeCompile
        run: ./gradlew nativeCompile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-native-linux
          path: |
            sbapsd-standalone-v3/build/native/nativeCompile
          retention-days: 5

  build-native-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: "22.3.1"
          java-version: "19"
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: "true"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle nativeCompile
        run: ./gradlew nativeCompile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-native-windows
          path: |
            sbapsd-standalone-v3/build/native/nativeCompile
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: [ test-v1, test-v2, test-v3, build-jvm, build-native-linux, build-native-windows ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Prepare Linux Artifacts
        run: |
          cd app-native-linux
          chmod +x sbapsd
          tar -czf $(cat gradle-artifact.txt)-linux-amd64.tar.gz sbapsd

      - name: Prepare Windows Artifacts
        run: |
          cd app-native-windows
          zip $(cat gradle-artifact.txt)-windows-amd64.zip sbapsd.exe

      - name: Build Release Changelog
        id: build-release-changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ".github/release-changelog-builder.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.build-release-changelog.outputs.changelog }}
          draft: true
          files: |
            app-jar/**/!(*-plain).jar
            app-native-linux/*.tar.gz
            app-native-windows/*.zip

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle publish
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
