name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:
  test-v2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '2.7.10' ]
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle run server
        run: ./gradlew runV1SBAServer -Psba.version=${{ matrix.java }} -Psba.server.port=8082

      - name: Await server up
        uses: cygnetdigital/wait_for_response@2.0.0
        with:
          url: http://localhost:8082/actuator/health
          responseCode: 200,500
          timeout: 15000
          interval: 500

      - name: Gradle test
        run: ./gradle :sbapsd-testing:sbapsd-testing-v2:test -Psba.server.port=8082

  build:
    runs-on: ubuntu-latest
    needs: [test-v2]
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: |
            sbapsd-app/build/libs/sbapsd-app-*.jar
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle publish
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish
